# Generated by Django 3.2 on 2021-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HobbiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='HobbiesApp.Hobby'),
        ),
    ]
