# Generated by Django 3.2.9 on 2021-11-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_communities',
            field=models.ManyToManyField(related_name='members', to='mainApp.Community'),
        ),
    ]
